services:
  web:
    build: ./
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/BooksShop/db.sqlite3:/app/db.sqlite3
      - ./backend/BooksShop/.:/app/.