# Generated by Django 4.2.13 on 2024-08-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='user',
        ),
    ]
