# Generated by Django 4.2.13 on 2024-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_user_id_basket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=96)),
                ('author', models.CharField(max_length=15)),
                ('date_usage', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
