# Generated by Django 4.2.13 on 2024-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_randomquote_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquote',
            name='date_usage',
            field=models.DateField(default=None, null=True),
        ),
    ]
