# Generated by Django 4.2.13 on 2024-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_randomquote_date_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquote',
            name='date_usage',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
