# Generated by Django 4.2.13 on 2024-09-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='active_for_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Rmnce', 'Romance'), ('Mystr', 'Mystery & Thriller'), ('Fntsy', 'Fantasy'), ('Sf-HP', 'Self-help'), ('Hrrr', 'Horror'), ('SF', 'Science Fiction'), ('CB', 'Children'), ('B/A', 'Biography/Autobiography'), ('HF', 'Historical Fiction'), ('OTHR', 'Other')], default='OTHR', max_length=50, null=True),
        ),
    ]
