# Generated by Django 4.2.13 on 2024-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_basket_active_for_order_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
